### ISSUE TITLE
AGM date needs agreeing on.

### ISSUE THREAD

**Issue by ScarletHg** [ChelmsfordMakerspace/space#1]
As the title says, we need to pick a date, time and place for the AGM to happen.

**Comment by Half-Shot** [comment]
I'm off exam pressure from June 1st.
Warmer weather would be preferrable ;).
July the 22nd is my last day in School.
Ideal time would be afternoons.
If we could secure the Hut or some other venue for some time **before** our usual 7:30 that would be great.

**Comment by ghost** [comment]
I'm good with pretty much any date. Some point after June 1st would be nice though. Afternoons are great.

**Comment by ScarletHg** [comment]
Well June 3rd we have our last meeting in the Scout Hut, would an earlier afternoon meeting on that day work?

**Comment by tomstacey** [comment]
Yes, that would work for me.

**Comment by Half-Shot** [comment]
I _can_ make that day although any day after the 6th would be easier for me. I've got my last exam on the 6th. Also @razyre mentioned he wanted it out of the exam period also.

**Comment by ScarletHg** [comment]
And it's WWDC until the 6th so I'll be watching the sessions as they come out.

7th until about the 28th then. Any preferences on what day of the week to narrow it down a bit?

**Comment by Half-Shot** [comment]
Deicded to be on the 13th of July @ 1PM

**Comment by ScarletHg** [comment]
Yup, now moving on to #10.

**Comment by ScarletHg** [comment]
Time has shifted back two hours to 3PM due to @tomstacey being in Reading that morning.
