### ISSUE TITLE
New membership models?

### ISSUE THREAD

**Issue by ScarletHg** [ChelmsfordMakerspace/space#11]
Not sure if the £2.50 a meeting option is still the best, especially if we end up going full time on a space.

**Comment by Half-Shot** [comment]
Not sure if this could work, but a price model that decreases the more you visit. Something like £3 a night, £7.50 for 3 nights. £25 for a year.
We could add to this with either covering the cost of events or alternatively not covering them and asking for donations on event nights.

**Comment by ScarletHg** [comment]
We decided to keep it the same, go subscription only when we get a space.
