### ISSUE TITLE
New payment methods.

### ISSUE THREAD

**Issue by ScarletHg** [ChelmsfordMakerspace/space#12]
Currently we accept cash only (with the exception of Kieran's Dogecoin). Ben did add a Google Checkout link to the site at one point but I never saw the money from that come through the accounts.

Should look up the possibility of using mobile payments with PayM or regular payments with Stripe or one of the many mobile chip and pin readers. Anything that isn't PayPal.

**Comment by Half-Shot** [comment]
Stripe looked good from what I read? Regular payments with discounts could fit a good new pricing model.

**Comment by ScarletHg** [comment]
We're going to look at accepting mobile payments through PayM, see #24.
