### ISSUE TITLE
Investigate short term funding or fundraising.

### ISSUE THREAD

**Issue by ScarletHg** [ChelmsfordMakerspace/space#13]
The space currently has a circular dependency, we can't charge enough for membership to cover the buying of a physical space until we have a space to offer.

Applying for grants and various funds has not worked. I would prefer if the money came from the community but it's not quite big enough to support that yet. Wider crowd funding is still an option.

**Comment by Half-Shot** [comment]
Events are one of the best ways to get funds and we could do a few things along that vein to do it:
- Raspberry Pi / Computer Board Hacking
- General Programming Tutorials
- Game/Software Jams
- Foss Night (I have a few ideas for this)
- Bimonthly Lan Partys could even be a way to charge people under our limits and gain cash. Its unique to our area, you could ask for money on food/drink, make it semi-frequently so it doesn't label us as a mess around group but the work and play type. It's also fairly cheap to run, only costing electrics + food. You could charge £4-£5 to have food included.

**Comment by ScarletHg** [comment]
Pi night went well (a little too well for the hut to cope!), game jam went relatively okay and LAN parties need to be slightly better organised in terms of games.

I'd be up for doing all those again and more, just not as the sole organiser!

**Comment by Half-Shot** [comment]
Game Jams might have wait until we have the ability to keep somewhere open all morning/day/evening . Pi night is pretty much set to go. LAN Parties can be organised by me. I can co-organise the other stuff, this is the stuff we can discuss in the AGM as well :).

**Comment by ScarletHg** [comment]
Already said this in the chat but I should put it here too, Could try opening a for-profit electronics and 3D print store. I get a lot of questions asking where to get stuff and especially emails asking if we can print various things from Thingiverse.

**Comment by Half-Shot** [comment]
Sounds good. Provided we don't get too deep burried in that it could work out well.

**Comment by ScarletHg** [comment]
We're going ahead with some kind of event for publicity, also likely going to Elephant and Castle Mini Maker Fare.

**Comment by ScarletHg** [comment]
I should note that I've closed this for now since it was discussed. Any ideas for fund raising from here should be opened as a new issue.
