### ISSUE TITLE
Skype chat replacement?

### ISSUE THREAD

**Issue by ScarletHg** [ChelmsfordMakerspace/space#2]
As said many times, Skype chats are not the best for Linux users and such.

**Comment by Half-Shot** [comment]
I use it, but its been at version 4.2 for so long now that eventually I'm going to hit issues. Furthermore, I would feel better not using a Microsoft program about these new snooping finds.

I would suggest IRC, but that tends not to work with keeping chat logs. Me and @razyre looked this up but most products were missing something.

**Comment by ScarletHg** [comment]
IRC is probably our best option if we were to pair it with something like [IRCAnywhere](http://ircanywhere.com/) for the scrollback and notification options. Could offer the web account as a membership benefit with anyone else free to setup their own bouncer or client to connect to IRC.

**Comment by Half-Shot** [comment]
I use IRC for my other communitys of between 30-150 and it works quite well. We use mumble if we require audio because it comes in great use. IRCAnywhere looks quite good.

**Comment by ScarletHg** [comment]
We're now trialling [Discourse](c.cmspace.org). We'll see how it goes for a month. May add IRC in to the fold if realtime, non-public chat is required.

**Comment by rossbishop** [comment]
No longer an issue.
Discourse is being retired, HipChat is the replacement for Skype. Sticking with GitHub.
