### ISSUE TITLE
Work out some way to make sure everybody is aware of meetings.

### ISSUE THREAD

**Issue by ScarletHg** [ChelmsfordMakerspace/space#27]
I screwed up and woke up about ten minutes before today's meeting. Because of this I didn't get to remind two people about the meeting.

This needs to not happen again, we need a way to remind a list of people about upcoming meetings. Be it an automated tweet from CM_Makerspace or an email notification.

**Comment by rossbishop** [comment]
Can you do either and what would people prefer? I will always know.

**Comment by Half-Shot** [comment]
Hipchat lets you email people when not in the room, and flashes notifications if you are.

**Comment by ScarletHg** [comment]
Using (at)All in HipChat and seems to be the way forward for notifications.
