### ISSUE TITLE
Look at other spaces finances and how they grew.

### ISSUE THREAD

**Issue by ScarletHg** [ChelmsfordMakerspace/space#32]
@davidlutton is going to look at other Hackspaces and Makerspaces to see how they grew from a tiny group with no space to wherever they are now. Also see what kind of finances they are running on to get an idea of how we should set expectations.

**Comment by tomstacey** [comment]
https://london.hackspace.org.uk/cost-of-hacking/

**Comment by ScarletHg** [comment]
We've mostly done this now, got a good idea of the costs and what they did to grow.
