### ISSUE TITLE
Game+BBQ 

### ISSUE THREAD

**Issue by Half-Shot** [ChelmsfordMakerspace/space#35]
We are having a LAN Party + a BBQ on the 

~~9th of August~~

**Need a new date!**

See [Google Docs](https://docs.google.com/document/d/1OLYJ77xoabW9uoLT_J4ygcqEIIINoWZU9R5xseR1JEs/edit#) for info

**Comment by tomstacey** [comment]
As you know folks, I'll be out of the country on the 9th. Just FYI

**Comment by Half-Shot** [comment]
:( Really wish we could move the date but almost everyone seems free on the 9th.

**Comment by Half-Shot** [comment]
Will probably get lots of videos from the event though :+1:

**Comment by tomstacey** [comment]
No, it’s fine - you guys are gamers and I’m not really anyway…  The only week I am around in August is week 34

**Comment by Half-Shot** [comment]
Postponed for ages and ages and _council please get us a space quick_

**Comment by ScarletHg** [comment]
I've got an almost complete plan, just requires an actual BBQ and somewhere to do it.

**Comment by Half-Shot** [comment]
Well if we can find item B (like somehow get a one off scout hut booking) then I'm sure I can find a BBQ from someone.
